samples/photo_album/config/routes.rb
PhotoAlbum::Application.routes.draw do
  resources :albums do
    resources :photos, :only => [:index, :new, :create]
  end

  root :to => 'albums#index'
end

samples/photo_album/app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title

  has_many :photos, :order => 'created_at DESC'

  def cover
    photos.first
  end
end

samples/photo_album/app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :title, :bytes, :image, :image_cache

  belongs_to :album

  mount_uploader :image, ImageUploader

  validates_presence_of :title, :image
end

samples/photo_album/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.where(id: params[:id]).includes(:photos).first
  end

  def new
    @album = Album.new(:title => "My album \##{1 + (Album.maximum(:id) || 0)}")
  end

  def create
    @album = Album.new(params[:album])

    if !@album.save
      @error = @album.errors.full_messages.join('. ')
      render "new"
      return
    end

    redirect_to @album
  end
end

samples/photo_album/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

samples/photo_album/app/controllers/photos_controller.rb
require 'digest/sha1'
class PhotosController < ApplicationController
  before_filter :set_album, only: [:new, :create]

  def new
    @photo = Photo.new(:title => "My photo \##{1 + (Photo.maximum(:id) || 0)}")
    if unsigned_mode?
      @unsigned = true
      # make sure we have the appropriate preset
      @preset_name = "sample_" + Digest::SHA1.hexdigest(Cloudinary.config.api_key + Cloudinary.config.api_secret)
      begin
        preset = Cloudinary::Api.upload_preset(@preset_name)
        if !preset["settings"]["return_delete_token"]
          Cloudinary::Api.update_upload_preset(@preset_name, :return_delete_token=>true)
        end
      rescue
        # An upload preset may contain (almost) all parameters that are used in upload. The following is just for illustration purposes
        Cloudinary::Api.create_upload_preset(:name => @preset_name, :unsigned => true, :folder => "preset_folder", :return_delete_token=>true)
      end
    end
    render view_for_new
  end

  def create
    @photo = @album.photos.build(params[:photo])

    # In through-the-server mode, the image is first uploaded to the Rails server.
    # When @photo is saved, Carrierwave uploads the image to Cloudinary.
    # The upload metadata (e.g. image size) is then available in the
    # uploader object of the model (@photo.image).
    # In direct mode, the image is uploaded to Cloudinary by the browser,
    # and upload metadata is available in JavaScript (see new_direct.html.erb).
    if !@photo.save
      @error = @photo.errors.full_messages.join('. ')
      render view_for_new
      return
    end
    if !direct_upload_mode?
      # In this sample, we want to store a part of the upload metadata
      # ("bytes" - the image size) in the Photo model.
      # In direct mode, we pass the image size via a hidden form field
      # filled by JavaScript (see new_direct.html.erb).
      # In through-the-server mode, we need to copy this field from Cloudinary
      # upload metadata. The metadata is only available after Carrierwave
      # performs the upload (in @photo.save), so we need to update the
      # already saved photo here.
      @photo.update_attributes(:bytes => @photo.image.metadata['bytes'])
      # Show upload metadata in the view
      @upload = @photo.image.metadata
    end
  end

  protected

  def set_album
    @album = Album.find(params[:album_id])
  end
  
  def direct_upload_mode?
    params[:direct].present?
  end
  
  def unsigned_mode?
    params[:unsigned].present?
  end
  
  def view_for_new
    direct_upload_mode? ? "new_direct" : "new"
  end

end

samples/photo_album/app/views/albums/index.html.erb
<div id="posterframe">
  <!-- This will render the fetched Facebook profile picture using Cloudinary according to the
       requested transformations -->
  <%= facebook_profile_image_tag("officialchucknorrispage", :format => "png",
    :transformation => [
      { :height => 95, :width => 95, :crop => "thumb", :gravity => "face", :effect => "sepia", :radius => 20 },
      { "angle" => 10 } ]) %>
</div>

<h1>Welcome!</h1>

<p>
  This is the main demo page of the PhotoAlbum sample Rails application of Cloudinary.<br />
  Here you can see all images you have uploaded to this Rails application and find some information on how
  to implement your own Rails application storing, manipulating and serving your photos using Cloudinary!
</p>

<p>
  All of the images you see here are transformed and served by Cloudinary. 
  For instance, the logo and the poster frame. 
  They are both generated in the cloud using the Cloudinary shortcut functions: fetch_image_tag and facebook_profile_image_tag. 
  These two pictures weren't even have to be uploaded to Cloudinary, they are retrieved by the service, transformed, cached and distributed through a CDN.
</p>

<h1>Your Albums:</h1>

<div class="actions">
  <a class="upload_link" href="<%= new_album_path %>">Add album</a>
</div>

<div class="albums">
  <% if @albums.empty? %>
    <p>No albums were added yet.</p>
  <% end %>

  <% @albums.each do |album| %>
    <div class="album">
      <h2>
        <%= link_to(album) do %>
          <%= album.title %>
          <%= image_tag(album.cover.image.thumbnail.url, :class => "thumbnail inline") %>
        <% end %>
      </h2>
    </div>
  <% end %>
</div>

samples/photo_album/app/views/albums/new.html.erb
<div class='basic_form'>
  <h1>New Album</h1>
  <%= form_for(@album) do |f| %>
    <div class="form_line">
      <%= f.label :title, "Title:" %>
      <div class="form_controls">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="form_line">
      <div class="form_controls">
        <%= f.submit "Submit Album" %>
        <% if @error %><span class="error"><%= @error %></span><% end %>
      </div>
    </div>
    <%= hidden_field_tag :direct, params[:direct] %>
  <% end %>
</div>

<a href="<%= albums_path %>" class="back_link">Back to albums</a>

samples/photo_album/app/views/albums/show.html.erb

<h1>Album: <%= @album.title %></h1>

<div class="actions">
  <a class="upload_link" href="<%= new_album_photo_path(@album) %>">Add photo</a>
  <a class="upload_link" href="<%= new_album_photo_path(@album, :direct => true) %>">Add photo (direct upload)</a>
  <a class="upload_link" href="<%= new_album_photo_path(@album, :direct => true, :unsigned => true) %>">Add photo (unsigned direct upload)</a>
</div>

<div class="albums">
  <% if @album.photos.empty? %>
    <p>No photos were added to the album yet.</p>
  <% end %>

  <% thumbs_params = { :format => "jpg", :height => 150, :width => 150, :class => "thumbnail inline" } %>
  <% @album.photos.each do |photo| %>
    <div class="photo">
      <h2><%= photo.title %></h2>
      <a href="<%= photo.image.url %>" target="_blank">
        <%= image_tag(photo.image.thumbnail.url, :class => "thumbnail inline") %>
      </a>

      <div class="less_info">
        <a href="#" class="toggle_info">Show transformations</a>
      </div>

      <div class="more_info">
        <a href="#" class="toggle_info">Hide transformations</a>
        <table class="thumbnails">
          <% transformations = [
              { :crop => "fill", :radius => 10, :height => 150, :width => 150 },
              { :crop => "scale", :height => 150, :width => 150 },
              { :crop => "fit", :height => 150, :width => 150 },
              { :crop => "thumb", :gravity => "face", :height => 150, :width => 150 },
              { :format => "png", :angle => 20, :transformation => { 
                :crop => "fill", :gravity => "north", :effect => "sepia", :height => 150, :width => 150 } }
            ] %>
          <% transformations.each do |image_params| %>
            <td>
              <div class="thumbnail_holder">
                <a target="_blank" href="<%= cloudinary_url(photo.image, image_params.dup) %>" > 
                  <%= cl_image_tag(photo.image, image_params.merge(:class => "thumbnail inline")) %>
                </a>
              </div>
              <table class="info">
                <% image_params.each_pair do |key, value| %>
                  <tr>
                    <td><%= key %></td>
                    <td><%= value.to_json %></td>
                  </tr>
                <% end %>  
              </table>
              <br/>
            </td>
          <% end %>
        </table>

        <div class="note">              
          Take a look at our documentation of <a href="http://cloudinary.com/documentation/image_transformations" target="_blank">Image Transformations</a> for a full list of supported transformations.
        </div>
      </div>
    </div>
  <% end %>
</div>

<a href="<%= albums_path %>" class="back_link">Back to albums</a>

<script type='text/javascript'>
  $('.toggle_info').click(function () {
    $(this).closest('.photo').toggleClass('show_more_info');
    return false;
  });
</script>

samples/photo_album/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoAlbum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon"
    href="<%= cloudinary_url("http://cloudinary.com/favicon.png", :type => "fetch") %>" />
</head>
<body>

<div id="logo">
  <!-- This will render the image fetched from a remote HTTP URL using Cloudinary -->
  <%= fetch_image_tag("http://cloudinary.com/images/logo.png") %>
</div>

<div class="content">
  <%= yield %>
</div>

</body>
</html>

samples/photo_album/app/views/photos/create.html.erb
<h1>Your photo was uploaded sucessfully!</h1>

<div class="photo">
  <h2><%= @photo.title %></h2>
  <a href="<%= @photo.image.url %>" target="_blank">
    <%= image_tag(@photo.image.thumbnail.url, :class => "thumbnail inline") %>
  </a>
</div>

<a href="<%= album_path(@album) %>" class="back_link">Back to album</a>

<% if @upload %>
  <div class="upload_details">
    <h2>Upload metadata:</h2>
    <table>
      <% @upload.each_pair do |k, v| %>
        <tr><td><%= k %></td><td><%= v.to_json %></td></tr>
      <% end %>
    </table>
  </div>
<% end %>    

samples/photo_album/app/views/photos/new.html.erb
<!-- A standard form for uploading images to your server -->
<div id='backend_upload'>
  <h1>New Photo</h1>
  <h2>Image file is uploaded through the server</h2>
  <%= form_for(@photo, :url => album_photos_path(@album)) do |f| %>
    <div class="form_line">
      <%= f.label :title, "Title:" %>
      <div class="form_controls">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="form_line">
      <%= f.label :image, "Image:" %>
      <div class="form_controls">
        <%= f.file_field :image %>
        <%= f.hidden_field(:image_cache) %>
      </div>
    </div>
    <div class="form_line">
      <div class="form_controls">
        <%= f.submit "Submit Photo" %>
        <% if @error %><span class="error"><%= @error %></span><% end %>
      </div>
    </div>
    <%= hidden_field_tag :direct, params[:direct] %>
  <% end %>
</div>

<a href="<%= album_path(@album) %>" class="back_link">Back to album</a>

samples/photo_album/app/views/photos/new_direct.html.erb
<div id="direct_upload" class="basic_form">
  <h1>New Photo</h1>
  <h2>Direct upload from the browser<% if @unsigned %>. Unsigned upload using a preset<% end %></h2>
  <p>You can also drag and drop an image file into the dashed area.</p>
  <%= form_for(@photo, :url => album_photos_path(@album)) do |f| %>
    <div class="form_line">
      <%= f.label :title, "Title:" %>
      <div class="form_controls">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="form_line">
      <%= f.label :image, "Image:" %>
      <div class="form_controls">
        <div class="upload_button_holder">
          <%= link_to("Upload", "#", :class => "upload_button") %>
          <% if @unsigned %>
            <%= f.cl_unsigned_image_upload(:image, @preset_name) %>
          <% else %>
            <%= f.cl_image_upload(:image, :return_delete_token=>true) %>
          <% end %>
        </div>
        <span class="status"></span>
      </div>
    </div>
    <div class="form_line">
      <div class="form_controls">
        <div class="preview"></div>
      </div>
    </div>
    <div class="form_line">
      <div class="form_controls">
        <%= f.submit "Submit Photo" %>
        <% if @error %><span class="error"><%= @error %></span><% end %>
      </div>
    </div>
    <%= f.hidden_field :bytes %>
    <%= hidden_field_tag :direct, params[:direct] %>
  <% end %>
</div>

<a href="<%= album_path(@album) %>" class="back_link">Back to album</a>

<div id="info"></div>

<!-- Configure Cloudinary jQuery plugin -->
<%= cloudinary_js_config %>

<script>
  $(document).ready(function() {
    // Cloudinary jQuery integration library uses jQuery File Upload widget
    // (see http://blueimp.github.io/jQuery-File-Upload/).
    // Any file input field with cloudinary-fileupload class is automatically
    // wrapped using the File Upload widget and configured for Cloudinary uploads.
    // You can further customize the configuration using .fileupload method
    // as we do below.
    $(".cloudinary-fileupload")
      .cloudinary_fileupload({
        // Uncomment the following lines to enable client side image resizing and valiation.
        // Make sure cloudinary/processing is included the js file
        //disableImageResize: false,
        //imageMaxWidth: 800,
        //imageMaxHeight: 600,
        //acceptFileTypes: /(\.|\/)(gif|jpe?g|png|bmp|ico)$/i,
        //maxFileSize: 20000000, // 20MB
        dropZone: "#direct_upload",
        start: function (e) {
          $(".status").text("Starting upload...");
        },
        progress: function (e, data) {
          $(".status").text("Uploading... " + Math.round((data.loaded * 100.0) / data.total) + "%");
        },
        fail: function (e, data) {
          $(".status").text("Upload failed");
        }
      })
      .off("cloudinarydone").on("cloudinarydone", function (e, data) {
        $("#photo_bytes").val(data.result.bytes);
        $(".status").text("");
        var preview = $(".preview").html('');
        $.cloudinary.image(data.result.public_id, {
          format: data.result.format, width: 50, height: 50, crop: "fit"
        }).appendTo(preview);

        $('<a/>').
          addClass('delete_by_token').
          attr({href: '#'}).
          data({delete_token: data.result.delete_token}).
          html('&times;').
          appendTo(preview).
          click(function(e) {
            e.preventDefault();
            $.cloudinary.delete_by_token($(this).data('delete_token')).done(function(){
              $('.preview').html('');
              $('#info').html('');
              $("#photo_bytes").val('');
              $('input[name="photo[image]"]').remove();
            }).fail(function() {
              $('.status').text("Cannot delete image");
          });
        });
        view_upload_details(data.result);
      });
    });

    function view_upload_details(upload) {
      // Build an html table out of the upload object
      var rows = [];
      $.each(upload, function(k,v){
        rows.push(
          $("<tr>")
            .append($("<td>").text(k))
            .append($("<td>").text(JSON.stringify(v))));
      });
      $("#info").html(
        $("<div class=\"upload_details\">")
          .append("<h2>Upload metadata:</h2>")
          .append($("<table>").append(rows)));
    }
</script>